### ISSUE TITLE
Probleme de Class Self

### ISSUE THREAD

**Issue by GwL-EricLL** [robinos33/wp-Api-FFTT#1]
Bonjour et Grand Merci.
J'ai une erreur lors de l'activation du PlugIn / WP 4.3.1

Fatal error: Class 'Self' not found in /srv/data/web/vhosts/www.fcjcaudan.fr/htdocs/wp-content/plugins/wp-api-fftt/classes/ParametresApiFFTT.php on line 13

Ping.....Pong

**Comment by robinos33** [comment]
Bonjour,
Effectivement j'ai rendu le repository public et fait mon push un peu trop tôt.
Je ferai une mise à jour très bientôt pour corriger ces problèmes d'activation.
Je vous tiens au courant !
A+

**Comment by GwL-EricLL** [comment]
Bonjour,

 

Si je peux vous rendre service (c’est le cas de le dire…) debug ou autre, n’hésitez pas à me faire signe, de plus je suis un peu dans la partie informatique.

Au plaisir de vous lire.

 

Eric LE LANNIER

8 Rue Eric Tabarly

56850 Caudan

 

0297055478

0683866951

 

De : Robin Aldasoro [mailto:notifications@github.com] 
Envoyé : jeudi 5 novembre 2015 10:23
À : robinos33/wp-Api-FFTT
Cc : GwL-EricLL
Objet : Re: [wp-Api-FFTT] Probleme de Class Self (#1)

 

Bonjour,
Effectivement j'ai rendu le repository public et fait mon push un peu trop tôt.
Je ferai une mise à jour très bientôt pour corriger ces problèmes d'activation.
Je vous tiens au courant !
A+

**Comment by robinos33** [comment]
Bonjour Eric,

J'ai fait une erreur lors de la création du repository sur GitHub.
Je vais devoir supprimer celui-là et le recréer (au nom de wp-api-fftt).
